title: Jackson Shands # your name (or website title) here
logo: "/images/GitHub_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  - Passionate and Integrity-driven Data Science professional transforming complex data into insightful and innovative solutions. Skilled in advanced analytics and cutting-edge technologies.
  <br><br>
  - Balancing technical expertise with excellent communication skills while effectively collaborating in cross-functional teams.
  - Expert in Statistical Analysis, Machine Learning, and Data Visualization.
  - Pursuing a Master of Applied Data Science from Syracuse University.
  - Solid expertise in Data and Business Analytics, Language Analytics, and Data Pipelines and Platforms.
  <br><br>
  <a href="https://www.linkedin.com/in/jackson-shands-b16062127/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
