title: Jackson Shands # your name (or website title) here
logo: "/images/GitHub_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Results-oriented Data Scientist with a proven track record of delivering innovative solutions that drive business growth and optimize performance. 
  Adept at leveraging cutting-edge technologies and advanced analytics to identify trends, uncover insights, and create actionable strategies.
  Strong collaborator with experience working in cross-functional teams and aligning stakeholders towards a shared vision. 
  Dynamic and versatile Data Science professional with a passion for transforming complex data into actionable insights that drive business success. 
  Expertise in Statistical Analysis, Machine Learning, Data Visualization, and Predictive Modeling.
  Proficient in Python, R, SQL, Hadoop, Apache Spark, Tableau, and various machine learning libraries.

 
  <br><br>
  Demonstrated ability to balance technical expertise with excellent communication and collaboration skills, working effectively with diverse teams to solve challenging problems.
  Pursuing a Master of Applied Data Science from Syracuse Univeristy School of Information Studies, with a strong foundation in Data and Business Analytics, Language Analytics, and Data Pipelines and Platforms 'statistical analysis, machine learning, and data-driven decision making.
  Key competencies include Data Mining, Text Analytics, Time Series Analysis, and Natural Language Processing.
  Fluent in Python, R, SQL, and a range of data science tools and platforms, including TensorFlow, Scikit-learn, and Jupyter Notebooks.
  <br><br>
  <a href="https://www.linkedin.com/in/jackson-shands-b16062127/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
