title: Jackson Shands # your name (or website title) here
logo: "/images/GitHub_pic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  - Integrity-driven Data Scientist with a track record of innovative solutions. Skilled in advanced analytics and cutting-edge technologies. Effective collaborator in cross-functional teams.
  <br><br>
  - Passionate Data Science professional transforming complex data into insights. Expert in Statistical Analysis, Machine Learning, and Data Visualization.
  - Balancing technical expertise with excellent communication skills. Pursuing a Master of Applied Data Science from Syracuse University.
  - Strong foundation in Data and Business Analytics, Language Analytics, and Data Pipelines.
  <br><br>
  <a href="https://www.linkedin.com/in/jackson-shands-b16062127/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
